// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_SimeAppsScr.h"
#include "screens/ui_CallScr.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * LargeBtn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * HideBtn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowBtn_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_sime_dirty_lines_png);    // assets/sime_dirty_lines.png
LV_IMG_DECLARE(ui_img_sime_happy_png);    // assets/sime_happy.png
LV_IMG_DECLARE(ui_img_sime_neutral_png);    // assets/sime_neutral.png
LV_IMG_DECLARE(ui_img_sime_sad_png);    // assets/sime_sad.png
LV_IMG_DECLARE(ui_img_sime_dying_png);    // assets/sime_dying.png
LV_IMG_DECLARE(ui_img_unselected_camera_png);    // assets/unselected_camera.png
LV_IMG_DECLARE(ui_img_icon_camera_png);    // assets/icon_camera.png
LV_IMG_DECLARE(ui_img_unselected_album_png);    // assets/unselected_album.png
LV_IMG_DECLARE(ui_img_icon_album_png);    // assets/Icon_album.png
LV_IMG_DECLARE(ui_img_unselected_music_png);    // assets/unselected_music.png
LV_IMG_DECLARE(ui_img_icon_music_png);    // assets/icon_music.png
LV_IMG_DECLARE(ui_img_unselected_phone_png);    // assets/unselected_phone.png
LV_IMG_DECLARE(ui_img_icon_phone_png);    // assets/icon_phone.png
LV_IMG_DECLARE(ui_img_unselected_cleaning_png);    // assets/unselected_cleaning.png
LV_IMG_DECLARE(ui_img_icon_cleaning_png);    // assets/icon_cleaning.png
LV_IMG_DECLARE(ui_img_unselected_food_png);    // assets/unselected_food.png
LV_IMG_DECLARE(ui_img_icon_food_png);    // assets/icon_food.png
LV_IMG_DECLARE(ui_img_unselected_hangup_png);    // assets/unselected_hangup.png
LV_IMG_DECLARE(ui_img_icon_hangup_png);    // assets/icon_hangup.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
