// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_SimeAppsScr.h"
#include "screens/ui_CallScr.h"
#include "screens/ui_IntercomScr.h"
#include "screens/ui_ContactsScr.h"
#include "screens/ui_FeedingCameraScr.h"
#include "screens/ui_ParentalLockScr.h"
#include "screens/ui_RowingGameScr.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * LargeBtn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * HideBtn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowBtn_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_sime_dirty_lines_png);    // assets/sime_dirty_lines.png
LV_IMG_DECLARE(ui_img_sime_happy_png);    // assets/sime_happy.png
LV_IMG_DECLARE(ui_img_sime_neutral_png);    // assets/sime_neutral.png
LV_IMG_DECLARE(ui_img_sime_dying_png);    // assets/sime_dying.png
LV_IMG_DECLARE(ui_img_music_note_png);    // assets/music_note.png
LV_IMG_DECLARE(ui_img_tata_png);    // assets/Tata.png
LV_IMG_DECLARE(ui_img_mama_png);    // assets/Mama.png
LV_IMG_DECLARE(ui_img_vila_png);    // assets/Vila.png
LV_IMG_DECLARE(ui_img_oz_png);    // assets/Oz.png
LV_IMG_DECLARE(ui_img_unselected_phone_red_png);    // assets/unselected_phone_red.png
LV_IMG_DECLARE(ui_img_kontakti_png);    // assets/Kontakti.png
LV_IMG_DECLARE(ui_img_unselected_back_arrow_png);    // assets/unselected_back_arrow.png
LV_IMG_DECLARE(ui_img_parentallock_png);    // assets/ParentalLock.png
LV_IMG_DECLARE(ui_img_rowboat_png);    // assets/rowboat.png
LV_IMG_DECLARE(ui_img_oar_png);    // assets/oar.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
