// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "ui.h"
#include "../../app_state.h"
#include "../../sime.h"
#include "../../audio.h"

static volatile int _curr_song = 5;

void enter_weslanje_cb(lv_event_t * e)
{
	set_app_state(APP_STATE_WESLANJE);
}

void enter_math_cb(lv_event_t * e)
{
	// Your code here
}

void enter_phone_cb(lv_event_t * e)
{
	set_app_state(APP_STATE_CONTACTS);
}

void enter_music_bttn(lv_event_t * e)
{
	audio_stop();
    audio_play(0, _curr_song);

    if ((++_curr_song) > 7) {
        _curr_song = 5;
    }
}

void feed_cb(lv_event_t * e)
{
	sime_feed_half();
}

void clean_cb(lv_event_t * e)
{
	sime_clean();
}

void exit_call_cb(lv_event_t * e)
{
	set_app_state(APP_STATE_CONTACTS);
}

void calling_mama_cb(lv_event_t * e)
{
	set_app_state(APP_STATE_CALL_SCREEN_1);
}

void calling_tata_cb(lv_event_t * e)
{
	set_app_state(APP_STATE_CALL_SCREEN_2);
}

void calling_spooderman_cb(lv_event_t * e)
{
	set_app_state(APP_STATE_CALL_SCREEN_3);
}

void calling_barbi_cb(lv_event_t * e)
{
	set_app_state(APP_STATE_CALL_SCREEN_4);
}

void exit_phone_cb(lv_event_t * e)
{
	set_app_state(APP_STATE_HOME_SCREEN);
}

void exit_veslanje_cb(lv_event_t * e)
{
	set_app_state(APP_STATE_HOME_SCREEN);
}
