// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_CALLSCR_H
#define UI_CALLSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CallScr
extern void ui_CallScr_screen_init(void);
extern void ui_CallScr_screen_destroy(void);
extern lv_obj_t * ui_CallScr;
extern lv_obj_t * ui_BackgroundGradient;
extern lv_obj_t * ui_ContactLabel;
extern lv_obj_t * ui_DurationLabel;
extern lv_obj_t * ui_HangBttn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

