// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_ContactsScr = NULL;
lv_obj_t * ui_BackgroundGradient2 = NULL;
lv_obj_t * ui_SimeNeutralImg2 = NULL;
lv_obj_t * ui_ContactsImg = NULL;
lv_obj_t * ui_KontaktiLabel = NULL;
lv_obj_t * ui_Div4 = NULL;
lv_obj_t * ui_Div3 = NULL;
lv_obj_t * ui_Div5 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_ExitContactsBttn = NULL;
lv_obj_t * ui_BarbiBttn = NULL;
lv_obj_t * ui_SpoodermanBttn = NULL;
lv_obj_t * ui_TataBttn = NULL;
lv_obj_t * ui_MamaBttn = NULL;
// event funtions
void ui_event_ExitContactsBttn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        exit_phone_cb(e);
    }
}

void ui_event_BarbiBttn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        calling_barbi_cb(e);
    }
}

void ui_event_SpoodermanBttn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        calling_spooderman_cb(e);
    }
}

void ui_event_TataBttn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        calling_tata_cb(e);
    }
}

void ui_event_MamaBttn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        calling_mama_cb(e);
    }
}

// build funtions

void ui_ContactsScr_screen_init(void)
{
    ui_ContactsScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ContactsScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackgroundGradient2 = lv_obj_create(ui_ContactsScr);
    lv_obj_set_width(ui_BackgroundGradient2, lv_pct(100));
    lv_obj_set_height(ui_BackgroundGradient2, lv_pct(100));
    lv_obj_set_align(ui_BackgroundGradient2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BackgroundGradient2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackgroundGradient2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackgroundGradient2, lv_color_hex(0x5428BA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackgroundGradient2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BackgroundGradient2, lv_color_hex(0x4F72F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BackgroundGradient2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackgroundGradient2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SimeNeutralImg2 = lv_img_create(ui_ContactsScr);
    lv_img_set_src(ui_SimeNeutralImg2, &ui_img_sime_neutral_png);
    lv_obj_set_width(ui_SimeNeutralImg2, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_height(ui_SimeNeutralImg2, LV_SIZE_CONTENT);    /// 96
    lv_obj_set_x(ui_SimeNeutralImg2, -23);
    lv_obj_set_y(ui_SimeNeutralImg2, 16);
    lv_obj_set_align(ui_SimeNeutralImg2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SimeNeutralImg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SimeNeutralImg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContactsImg = lv_img_create(ui_ContactsScr);
    lv_img_set_src(ui_ContactsImg, &ui_img_unselected_phone_red_png);
    lv_obj_set_width(ui_ContactsImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContactsImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContactsImg, -12);
    lv_obj_set_y(ui_ContactsImg, 12);
    lv_obj_set_align(ui_ContactsImg, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ContactsImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ContactsImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KontaktiLabel = lv_img_create(ui_ContactsScr);
    lv_img_set_src(ui_KontaktiLabel, &ui_img_kontakti_png);
    lv_obj_set_width(ui_KontaktiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KontaktiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KontaktiLabel, 115);
    lv_obj_set_y(ui_KontaktiLabel, 22);
    lv_obj_set_align(ui_KontaktiLabel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KontaktiLabel, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_KontaktiLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Div4 = lv_obj_create(ui_ContactsScr);
    lv_obj_set_width(ui_Div4, 1);
    lv_obj_set_height(ui_Div4, 100);
    lv_obj_set_x(ui_Div4, -25);
    lv_obj_set_y(ui_Div4, 24);
    lv_obj_set_align(ui_Div4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Div4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Div3 = lv_obj_create(ui_ContactsScr);
    lv_obj_set_width(ui_Div3, 1);
    lv_obj_set_height(ui_Div3, 100);
    lv_obj_set_x(ui_Div3, 25);
    lv_obj_set_y(ui_Div3, 24);
    lv_obj_set_align(ui_Div3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Div3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Div5 = lv_obj_create(ui_ContactsScr);
    lv_obj_set_width(ui_Div5, 1);
    lv_obj_set_height(ui_Div5, 100);
    lv_obj_set_x(ui_Div5, -77);
    lv_obj_set_y(ui_Div5, 24);
    lv_obj_set_align(ui_Div5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Div5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_ContactsScr);
    lv_img_set_src(ui_Image1, &ui_img_unselected_back_arrow_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 12);
    lv_obj_set_y(ui_Image1, -12);
    lv_obj_set_align(ui_Image1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ExitContactsBttn = lv_obj_create(ui_ContactsScr);
    lv_obj_set_width(ui_ExitContactsBttn, 64);
    lv_obj_set_height(ui_ExitContactsBttn, 64);
    lv_obj_set_x(ui_ExitContactsBttn, 12);
    lv_obj_set_y(ui_ExitContactsBttn, -12);
    lv_obj_set_align(ui_ExitContactsBttn, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_ExitContactsBttn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ExitContactsBttn, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExitContactsBttn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ExitContactsBttn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ExitContactsBttn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ExitContactsBttn, 16, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_ExitContactsBttn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ExitContactsBttn, 80, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_ExitContactsBttn, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_BarbiBttn = lv_imgbtn_create(ui_ContactsScr);
    lv_imgbtn_set_src(ui_BarbiBttn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_oz_png, NULL);
    lv_obj_set_width(ui_BarbiBttn, 44);
    lv_obj_set_height(ui_BarbiBttn, 81);
    lv_obj_set_x(ui_BarbiBttn, 38);
    lv_obj_set_y(ui_BarbiBttn, 24);

    ui_SpoodermanBttn = lv_imgbtn_create(ui_ContactsScr);
    lv_imgbtn_set_src(ui_SpoodermanBttn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_vila_png, NULL);
    lv_obj_set_width(ui_SpoodermanBttn, 44);
    lv_obj_set_height(ui_SpoodermanBttn, 184);
    lv_obj_set_x(ui_SpoodermanBttn, 89);
    lv_obj_set_y(ui_SpoodermanBttn, 24);

    ui_TataBttn = lv_imgbtn_create(ui_ContactsScr);
    lv_imgbtn_set_src(ui_TataBttn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_tata_png, NULL);
    lv_obj_set_width(ui_TataBttn, 44);
    lv_obj_set_height(ui_TataBttn, 73);
    lv_obj_set_x(ui_TataBttn, 140);
    lv_obj_set_y(ui_TataBttn, 24);

    ui_MamaBttn = lv_imgbtn_create(ui_ContactsScr);
    lv_imgbtn_set_src(ui_MamaBttn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_mama_png, NULL);
    lv_obj_set_width(ui_MamaBttn, 44);
    lv_obj_set_height(ui_MamaBttn, 89);
    lv_obj_set_x(ui_MamaBttn, 191);
    lv_obj_set_y(ui_MamaBttn, 24);

    lv_obj_add_event_cb(ui_ExitContactsBttn, ui_event_ExitContactsBttn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BarbiBttn, ui_event_BarbiBttn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SpoodermanBttn, ui_event_SpoodermanBttn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TataBttn, ui_event_TataBttn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MamaBttn, ui_event_MamaBttn, LV_EVENT_ALL, NULL);

}

void ui_ContactsScr_screen_destroy(void)
{
    if(ui_ContactsScr) lv_obj_del(ui_ContactsScr);

    // NULL screen variables
    ui_ContactsScr = NULL;
    ui_BackgroundGradient2 = NULL;
    ui_SimeNeutralImg2 = NULL;
    ui_ContactsImg = NULL;
    ui_KontaktiLabel = NULL;
    ui_Div4 = NULL;
    ui_Div3 = NULL;
    ui_Div5 = NULL;
    ui_Image1 = NULL;
    ui_ExitContactsBttn = NULL;
    ui_BarbiBttn = NULL;
    ui_SpoodermanBttn = NULL;
    ui_TataBttn = NULL;
    ui_MamaBttn = NULL;

}
