// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_CallScr = NULL;
lv_obj_t * ui_BackgroundGradient = NULL;
lv_obj_t * ui_TataLabel2 = NULL;
lv_obj_t * ui_MamaLabel2 = NULL;
lv_obj_t * ui_SpoodermanLabel2 = NULL;
lv_obj_t * ui_BarbiLabel2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_ExitContactsBttn2 = NULL;
lv_obj_t * ui_SimeNeutralImg3 = NULL;
// event funtions
void ui_event_ExitContactsBttn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        exit_call_cb(e);
    }
}

// build funtions

void ui_CallScr_screen_init(void)
{
    ui_CallScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CallScr, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackgroundGradient = lv_obj_create(ui_CallScr);
    lv_obj_set_width(ui_BackgroundGradient, lv_pct(100));
    lv_obj_set_height(ui_BackgroundGradient, lv_pct(100));
    lv_obj_set_align(ui_BackgroundGradient, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BackgroundGradient, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackgroundGradient, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackgroundGradient, lv_color_hex(0x271BE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackgroundGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BackgroundGradient, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BackgroundGradient, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BackgroundGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BackgroundGradient, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackgroundGradient, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TataLabel2 = lv_img_create(ui_CallScr);
    lv_img_set_src(ui_TataLabel2, &ui_img_tata_png);
    lv_obj_set_width(ui_TataLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TataLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TataLabel2, -68);
    lv_obj_set_y(ui_TataLabel2, 0);
    lv_obj_set_align(ui_TataLabel2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_TataLabel2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TataLabel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MamaLabel2 = lv_img_create(ui_CallScr);
    lv_img_set_src(ui_MamaLabel2, &ui_img_mama_png);
    lv_obj_set_width(ui_MamaLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MamaLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MamaLabel2, -68);
    lv_obj_set_y(ui_MamaLabel2, 0);
    lv_obj_set_align(ui_MamaLabel2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_MamaLabel2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MamaLabel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpoodermanLabel2 = lv_img_create(ui_CallScr);
    lv_img_set_src(ui_SpoodermanLabel2, &ui_img_vila_png);
    lv_obj_set_width(ui_SpoodermanLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpoodermanLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpoodermanLabel2, -68);
    lv_obj_set_y(ui_SpoodermanLabel2, 0);
    lv_obj_set_align(ui_SpoodermanLabel2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_SpoodermanLabel2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SpoodermanLabel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarbiLabel2 = lv_img_create(ui_CallScr);
    lv_img_set_src(ui_BarbiLabel2, &ui_img_oz_png);
    lv_obj_set_height(ui_BarbiLabel2, 84);
    lv_obj_set_width(ui_BarbiLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_BarbiLabel2, -68);
    lv_obj_set_y(ui_BarbiLabel2, 0);
    lv_obj_set_align(ui_BarbiLabel2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_BarbiLabel2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BarbiLabel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_CallScr);
    lv_img_set_src(ui_Image2, &ui_img_unselected_phone_red_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image2, 32);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ExitContactsBttn2 = lv_obj_create(ui_CallScr);
    lv_obj_set_width(ui_ExitContactsBttn2, 64);
    lv_obj_set_height(ui_ExitContactsBttn2, 64);
    lv_obj_set_x(ui_ExitContactsBttn2, 32);
    lv_obj_set_y(ui_ExitContactsBttn2, 0);
    lv_obj_set_align(ui_ExitContactsBttn2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ExitContactsBttn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ExitContactsBttn2, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExitContactsBttn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ExitContactsBttn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ExitContactsBttn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ExitContactsBttn2, 16, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_ExitContactsBttn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ExitContactsBttn2, 80, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_ExitContactsBttn2, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SimeNeutralImg3 = lv_img_create(ui_CallScr);
    lv_img_set_src(ui_SimeNeutralImg3, &ui_img_sime_neutral_png);
    lv_obj_set_width(ui_SimeNeutralImg3, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_height(ui_SimeNeutralImg3, LV_SIZE_CONTENT);    /// 96
    lv_obj_set_x(ui_SimeNeutralImg3, -13);
    lv_obj_set_y(ui_SimeNeutralImg3, 86);
    lv_obj_set_align(ui_SimeNeutralImg3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SimeNeutralImg3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SimeNeutralImg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ExitContactsBttn2, ui_event_ExitContactsBttn2, LV_EVENT_ALL, NULL);

}

void ui_CallScr_screen_destroy(void)
{
    if(ui_CallScr) lv_obj_del(ui_CallScr);

    // NULL screen variables
    ui_CallScr = NULL;
    ui_BackgroundGradient = NULL;
    ui_TataLabel2 = NULL;
    ui_MamaLabel2 = NULL;
    ui_SpoodermanLabel2 = NULL;
    ui_BarbiLabel2 = NULL;
    ui_Image2 = NULL;
    ui_ExitContactsBttn2 = NULL;
    ui_SimeNeutralImg3 = NULL;

}
