// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_CallScr = NULL;
lv_obj_t * ui_BackgroundGradient = NULL;
lv_obj_t * ui_ContactLabel = NULL;
lv_obj_t * ui_DurationLabel = NULL;
lv_obj_t * ui_HangBttn = NULL;
// event funtions

// build funtions

void ui_CallScr_screen_init(void)
{
    ui_CallScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CallScr, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackgroundGradient = lv_obj_create(ui_CallScr);
    lv_obj_set_width(ui_BackgroundGradient, lv_pct(100));
    lv_obj_set_height(ui_BackgroundGradient, lv_pct(100));
    lv_obj_set_align(ui_BackgroundGradient, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BackgroundGradient, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackgroundGradient, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BackgroundGradient, lv_color_hex(0x271BE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BackgroundGradient, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BackgroundGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BackgroundGradient, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContactLabel = lv_label_create(ui_CallScr);
    lv_obj_set_width(ui_ContactLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContactLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContactLabel, 0);
    lv_obj_set_y(ui_ContactLabel, 64);
    lv_obj_set_align(ui_ContactLabel, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_ContactLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ContactLabel, "Mama");

    ui_DurationLabel = lv_label_create(ui_CallScr);
    lv_obj_set_width(ui_DurationLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DurationLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DurationLabel, 0);
    lv_obj_set_y(ui_DurationLabel, 84);
    lv_obj_set_align(ui_DurationLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DurationLabel, "00:30");
    lv_obj_set_style_text_color(ui_DurationLabel, lv_color_hex(0x4C4C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DurationLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HangBttn = lv_imgbtn_create(ui_CallScr);
    lv_imgbtn_set_src(ui_HangBttn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_unselected_hangup_png, NULL);
    lv_imgbtn_set_src(ui_HangBttn, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon_hangup_png, NULL);
    lv_obj_set_width(ui_HangBttn, 64);
    lv_obj_set_height(ui_HangBttn, 64);
    lv_obj_set_x(ui_HangBttn, 0);
    lv_obj_set_y(ui_HangBttn, -32);
    lv_obj_set_align(ui_HangBttn, LV_ALIGN_BOTTOM_MID);

}

void ui_CallScr_screen_destroy(void)
{
    if(ui_CallScr) lv_obj_del(ui_CallScr);

    // NULL screen variables
    ui_CallScr = NULL;
    ui_BackgroundGradient = NULL;
    ui_ContactLabel = NULL;
    ui_DurationLabel = NULL;
    ui_HangBttn = NULL;

}
