// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_CONTACTSSCR_H
#define UI_CONTACTSSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ContactsScr
extern void ui_ContactsScr_screen_init(void);
extern void ui_ContactsScr_screen_destroy(void);
extern lv_obj_t * ui_ContactsScr;
extern lv_obj_t * ui_BackgroundGradient2;
extern lv_obj_t * ui_SimeNeutralImg2;
extern lv_obj_t * ui_ContactsImg;
extern lv_obj_t * ui_KontaktiLabel;
extern lv_obj_t * ui_Div4;
extern lv_obj_t * ui_Div3;
extern lv_obj_t * ui_Div5;
extern lv_obj_t * ui_Image1;
extern void ui_event_ExitContactsBttn(lv_event_t * e);
extern lv_obj_t * ui_ExitContactsBttn;
extern void ui_event_BarbiBttn(lv_event_t * e);
extern lv_obj_t * ui_BarbiBttn;
extern void ui_event_SpoodermanBttn(lv_event_t * e);
extern lv_obj_t * ui_SpoodermanBttn;
extern void ui_event_TataBttn(lv_event_t * e);
extern lv_obj_t * ui_TataBttn;
extern void ui_event_MamaBttn(lv_event_t * e);
extern lv_obj_t * ui_MamaBttn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

