// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_FEEDINGCAMERASCR_H
#define UI_FEEDINGCAMERASCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FeedingCameraScr
extern void ui_FeedingCameraScr_screen_init(void);
extern void ui_FeedingCameraScr_screen_destroy(void);
extern lv_obj_t * ui_FeedingCameraScr;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

