// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_FeedingCameraScr = NULL;
// event funtions

// build funtions

void ui_FeedingCameraScr_screen_init(void)
{
    ui_FeedingCameraScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FeedingCameraScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_FeedingCameraScr_screen_destroy(void)
{
    if(ui_FeedingCameraScr) lv_obj_del(ui_FeedingCameraScr);

    // NULL screen variables
    ui_FeedingCameraScr = NULL;

}
