// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_IntercomScr = NULL;
lv_obj_t * ui_BackgroundGradient1 = NULL;
lv_obj_t * ui_MamaLabel3 = NULL;
lv_obj_t * ui_SimeHappyImg2 = NULL;
// event funtions
void ui_event_MamaLabel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        calling_mama_cb(e);
    }
}

// build funtions

void ui_IntercomScr_screen_init(void)
{
    ui_IntercomScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IntercomScr, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackgroundGradient1 = lv_obj_create(ui_IntercomScr);
    lv_obj_set_width(ui_BackgroundGradient1, lv_pct(100));
    lv_obj_set_height(ui_BackgroundGradient1, lv_pct(100));
    lv_obj_set_align(ui_BackgroundGradient1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BackgroundGradient1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackgroundGradient1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackgroundGradient1, lv_color_hex(0xC11BE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackgroundGradient1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BackgroundGradient1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BackgroundGradient1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BackgroundGradient1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BackgroundGradient1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackgroundGradient1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MamaLabel3 = lv_img_create(ui_IntercomScr);
    lv_img_set_src(ui_MamaLabel3, &ui_img_mama_png);
    lv_obj_set_width(ui_MamaLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MamaLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MamaLabel3, -68);
    lv_obj_set_y(ui_MamaLabel3, 0);
    lv_obj_set_align(ui_MamaLabel3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_MamaLabel3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MamaLabel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SimeHappyImg2 = lv_img_create(ui_IntercomScr);
    lv_img_set_src(ui_SimeHappyImg2, &ui_img_sime_happy_png);
    lv_obj_set_width(ui_SimeHappyImg2, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_height(ui_SimeHappyImg2, LV_SIZE_CONTENT);    /// 96
    lv_obj_set_x(ui_SimeHappyImg2, 106);
    lv_obj_set_y(ui_SimeHappyImg2, 0);
    lv_obj_set_align(ui_SimeHappyImg2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SimeHappyImg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SimeHappyImg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_MamaLabel3, ui_event_MamaLabel3, LV_EVENT_ALL, NULL);

}

void ui_IntercomScr_screen_destroy(void)
{
    if(ui_IntercomScr) lv_obj_del(ui_IntercomScr);

    // NULL screen variables
    ui_IntercomScr = NULL;
    ui_BackgroundGradient1 = NULL;
    ui_MamaLabel3 = NULL;
    ui_SimeHappyImg2 = NULL;

}
