// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_INTERCOMSCR_H
#define UI_INTERCOMSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_IntercomScr
extern void ui_IntercomScr_screen_init(void);
extern void ui_IntercomScr_screen_destroy(void);
extern lv_obj_t * ui_IntercomScr;
extern lv_obj_t * ui_BackgroundGradient1;
extern void ui_event_MamaLabel3(lv_event_t * e);
extern lv_obj_t * ui_MamaLabel3;
extern lv_obj_t * ui_SimeHappyImg2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

