// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_PARENTALLOCKSCR_H
#define UI_PARENTALLOCKSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ParentalLockScr
extern void ui_ParentalLockScr_screen_init(void);
extern void ui_ParentalLockScr_screen_destroy(void);
extern lv_obj_t * ui_ParentalLockScr;
extern lv_obj_t * ui_BackgroundGradient4;
extern lv_obj_t * ui_SimeVeryUnhappyImg2;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

