// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_ParentalLockScr = NULL;
lv_obj_t * ui_BackgroundGradient4 = NULL;
lv_obj_t * ui_SimeVeryUnhappyImg2 = NULL;
lv_obj_t * ui_Image3 = NULL;
// event funtions

// build funtions

void ui_ParentalLockScr_screen_init(void)
{
    ui_ParentalLockScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ParentalLockScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackgroundGradient4 = lv_obj_create(ui_ParentalLockScr);
    lv_obj_set_width(ui_BackgroundGradient4, lv_pct(100));
    lv_obj_set_height(ui_BackgroundGradient4, lv_pct(100));
    lv_obj_set_align(ui_BackgroundGradient4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BackgroundGradient4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackgroundGradient4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackgroundGradient4, lv_color_hex(0xA6AFBB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackgroundGradient4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackgroundGradient4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SimeVeryUnhappyImg2 = lv_img_create(ui_ParentalLockScr);
    lv_img_set_src(ui_SimeVeryUnhappyImg2, &ui_img_sime_dying_png);
    lv_obj_set_width(ui_SimeVeryUnhappyImg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SimeVeryUnhappyImg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SimeVeryUnhappyImg2, 129);
    lv_obj_set_y(ui_SimeVeryUnhappyImg2, 0);
    lv_obj_set_align(ui_SimeVeryUnhappyImg2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SimeVeryUnhappyImg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SimeVeryUnhappyImg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_ParentalLockScr);
    lv_img_set_src(ui_Image3, &ui_img_parentallock_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 75);
    lv_obj_set_y(ui_Image3, 0);
    lv_obj_set_align(ui_Image3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ParentalLockScr_screen_destroy(void)
{
    if(ui_ParentalLockScr) lv_obj_del(ui_ParentalLockScr);

    // NULL screen variables
    ui_ParentalLockScr = NULL;
    ui_BackgroundGradient4 = NULL;
    ui_SimeVeryUnhappyImg2 = NULL;
    ui_Image3 = NULL;

}
