// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_ROWINGGAMESCR_H
#define UI_ROWINGGAMESCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RowingGameScr
extern void ui_RowingGameScr_screen_init(void);
extern void ui_RowingGameScr_screen_destroy(void);
extern lv_obj_t * ui_RowingGameScr;
extern lv_obj_t * ui_BackgroundGradient5;
extern lv_obj_t * ui_SimeNeutralImg4;
extern lv_obj_t * ui_RowboatImg;
extern lv_obj_t * ui_OarLeftImg;
extern lv_obj_t * ui_OarRightImg;
extern void ui_event_ExitWeslanjeBttn(lv_event_t * e);
extern lv_obj_t * ui_ExitWeslanjeBttn;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_RowingStatusLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

