// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_RowingGameScr = NULL;
lv_obj_t * ui_BackgroundGradient5 = NULL;
lv_obj_t * ui_SimeNeutralImg4 = NULL;
lv_obj_t * ui_RowboatImg = NULL;
lv_obj_t * ui_OarLeftImg = NULL;
lv_obj_t * ui_OarRightImg = NULL;
lv_obj_t * ui_ExitWeslanjeBttn = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_RowingStatusLabel = NULL;
// event funtions
void ui_event_ExitWeslanjeBttn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        exit_veslanje_cb(e);
    }
}

// build funtions

void ui_RowingGameScr_screen_init(void)
{
    ui_RowingGameScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RowingGameScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackgroundGradient5 = lv_obj_create(ui_RowingGameScr);
    lv_obj_set_width(ui_BackgroundGradient5, lv_pct(100));
    lv_obj_set_height(ui_BackgroundGradient5, lv_pct(100));
    lv_obj_set_align(ui_BackgroundGradient5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BackgroundGradient5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackgroundGradient5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackgroundGradient5, lv_color_hex(0xCEDAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackgroundGradient5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BackgroundGradient5, lv_color_hex(0x273DBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BackgroundGradient5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BackgroundGradient5, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BackgroundGradient5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackgroundGradient5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SimeNeutralImg4 = lv_img_create(ui_RowingGameScr);
    lv_img_set_src(ui_SimeNeutralImg4, &ui_img_sime_neutral_png);
    lv_obj_set_width(ui_SimeNeutralImg4, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_height(ui_SimeNeutralImg4, LV_SIZE_CONTENT);    /// 96
    lv_obj_set_x(ui_SimeNeutralImg4, 34);
    lv_obj_set_y(ui_SimeNeutralImg4, 16);
    lv_obj_set_align(ui_SimeNeutralImg4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SimeNeutralImg4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SimeNeutralImg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_SimeNeutralImg4, 30, 30);
    lv_img_set_angle(ui_SimeNeutralImg4, 2);
    lv_img_set_zoom(ui_SimeNeutralImg4, 230);

    ui_RowboatImg = lv_img_create(ui_RowingGameScr);
    lv_img_set_src(ui_RowboatImg, &ui_img_rowboat_png);
    lv_obj_set_width(ui_RowboatImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RowboatImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RowboatImg, -80);
    lv_obj_set_y(ui_RowboatImg, 32);
    lv_obj_set_align(ui_RowboatImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RowboatImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RowboatImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OarLeftImg = lv_img_create(ui_RowingGameScr);
    lv_img_set_src(ui_OarLeftImg, &ui_img_oar_png);
    lv_obj_set_width(ui_OarLeftImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OarLeftImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OarLeftImg, -103);
    lv_obj_set_y(ui_OarLeftImg, 49);
    lv_obj_set_align(ui_OarLeftImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OarLeftImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OarLeftImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OarRightImg = lv_img_create(ui_RowingGameScr);
    lv_img_set_src(ui_OarRightImg, &ui_img_oar_png);
    lv_obj_set_width(ui_OarRightImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OarRightImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OarRightImg, -68);
    lv_obj_set_y(ui_OarRightImg, 49);
    lv_obj_set_align(ui_OarRightImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OarRightImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OarRightImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ExitWeslanjeBttn = lv_obj_create(ui_RowingGameScr);
    lv_obj_set_width(ui_ExitWeslanjeBttn, 64);
    lv_obj_set_height(ui_ExitWeslanjeBttn, 64);
    lv_obj_set_x(ui_ExitWeslanjeBttn, 0);
    lv_obj_set_y(ui_ExitWeslanjeBttn, -12);
    lv_obj_set_align(ui_ExitWeslanjeBttn, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_ExitWeslanjeBttn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ExitWeslanjeBttn, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExitWeslanjeBttn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ExitWeslanjeBttn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ExitWeslanjeBttn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ExitWeslanjeBttn, 16, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_ExitWeslanjeBttn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ExitWeslanjeBttn, 80, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_ExitWeslanjeBttn, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image5 = lv_img_create(ui_RowingGameScr);
    lv_img_set_src(ui_Image5, &ui_img_unselected_back_arrow_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 0);
    lv_obj_set_y(ui_Image5, -12);
    lv_obj_set_align(ui_Image5, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_RowingGameScr);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -12);
    lv_obj_set_y(ui_Label1, -80);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Prevrnuo sam se!\nPomozite mi veslanjem tipkama 4 i 2 ");

    ui_RowingStatusLabel = lv_label_create(ui_RowingGameScr);
    lv_obj_set_width(ui_RowingStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RowingStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RowingStatusLabel, 82);
    lv_obj_set_y(ui_RowingStatusLabel, 12);
    lv_obj_set_align(ui_RowingStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RowingStatusLabel, "7 s\n67 veslanja\nHS: 100");
    lv_obj_set_style_text_color(ui_RowingStatusLabel, lv_color_hex(0xB5FFF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RowingStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ExitWeslanjeBttn, ui_event_ExitWeslanjeBttn, LV_EVENT_ALL, NULL);

}

void ui_RowingGameScr_screen_destroy(void)
{
    if(ui_RowingGameScr) lv_obj_del(ui_RowingGameScr);

    // NULL screen variables
    ui_RowingGameScr = NULL;
    ui_BackgroundGradient5 = NULL;
    ui_SimeNeutralImg4 = NULL;
    ui_RowboatImg = NULL;
    ui_OarLeftImg = NULL;
    ui_OarRightImg = NULL;
    ui_ExitWeslanjeBttn = NULL;
    ui_Image5 = NULL;
    ui_Label1 = NULL;
    ui_RowingStatusLabel = NULL;

}
