// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_SIMEAPPSSCR_H
#define UI_SIMEAPPSSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SimeAppsScr
extern void ui_SimeAppsScr_screen_init(void);
extern void ui_SimeAppsScr_screen_destroy(void);
extern lv_obj_t * ui_SimeAppsScr;
extern lv_obj_t * ui_BackgroundImg;
extern lv_obj_t * ui_SimeContainer;
extern lv_obj_t * ui_SimeDirtyLinesImg;
extern lv_obj_t * ui_SimeHappyImg;
extern lv_obj_t * ui_SimeNeutralImg;
extern lv_obj_t * ui_SimeVeryUnhappyImg;
extern lv_obj_t * ui_MusicNoteImg1;
extern lv_obj_t * ui_MusicNoteImg2;
extern lv_obj_t * ui_AppsContainer;
extern void ui_event_WeslanjeBttn(lv_event_t * e);
extern lv_obj_t * ui_WeslanjeBttn;
extern void ui_event_PhoneBttn(lv_event_t * e);
extern lv_obj_t * ui_PhoneBttn;
extern void ui_event_MusicBttn(lv_event_t * e);
extern lv_obj_t * ui_MusicBttn;
extern lv_obj_t * ui_SimeActionContainer;
extern void ui_event_FeedBttn(lv_event_t * e);
extern lv_obj_t * ui_FeedBttn;
extern void ui_event_CleanBttn(lv_event_t * e);
extern lv_obj_t * ui_CleanBttn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

