// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_SIMEAPPSSCR_H
#define UI_SIMEAPPSSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SimeAppsScr
extern void ui_SimeAppsScr_screen_init(void);
extern void ui_SimeAppsScr_screen_destroy(void);
extern lv_obj_t * ui_SimeAppsScr;
extern lv_obj_t * ui_BackgroundImg;
extern lv_obj_t * ui_SimeContainer;
extern lv_obj_t * ui_SimeDirtyLinesImg;
extern lv_obj_t * ui_SimeHappyImg;
extern lv_obj_t * ui_SimeNeutralImg;
extern lv_obj_t * ui_SimeSadImg;
extern lv_obj_t * ui_SimeVeryUnhappyImg;
extern lv_obj_t * ui_SimeBttn;
extern lv_obj_t * ui_AppsContainer;
extern lv_obj_t * ui_CameraBttn;
extern lv_obj_t * ui_GalleryBttn;
extern lv_obj_t * ui_MusicBttn;
extern void ui_event_PhoneBttn(lv_event_t * e);
extern lv_obj_t * ui_PhoneBttn;
extern lv_obj_t * ui_SimeActionContainer;
extern lv_obj_t * ui_SimeCleanBttn;
extern lv_obj_t * ui_SimeFeedBttn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

